config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    root to: 'pages#welcome', constraints: RouteConstraints::NoUserRequiredConstraint.new, as: :nonauthenticated_root
    root to: 'results#index', constraints: RouteConstraints::UserRequiredConstraint.new, as: :authenticated_root

    resources :users, only: [:new, :create]
    get '/sign_up', to: 'users#new', as: :sign_up

    resources :sessions, only: [:new, :create, :destroy]
    get '/sign_in', to: 'sessions#new', as: :sign_in
    delete '/sign_out', to: 'sessions#destroy', as: :sign_out

    resources :acts, except: [:new, :edit, :show]
    resources :results, except: [:new, :edit, :show] do
      collection do
        get :data
      end
    end
  end
end

app/models/act.rb
class Act < ActiveRecord::Base
  belongs_to :user
  has_many :results

  validates :title, :points, presence: true
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :act

  validates :date, :act_id, presence: true

  scope :for, ->(date) { where(date: date) }

  def as_json(options = nil)
    super.merge(act.as_json.slice('title', 'points')) if act
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :acts
  has_many :results, through: :acts

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true,
                    email_format: { message: I18n.t('activerecord.errors.models.user.attributes.email.email_format') }
  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  def index
    @acts = current_user.acts
  end

  def create
    @act = Act.new(act_params)
    @act.user_id = current_user.id

    if @act.save
      render json: @act
    else
      render json: @act.errors, status: :unprocessable_entity
    end
  end

  def update
    @act = Act.find(params[:id])
    if @act.update(act_params)
      render json: @act
    else
      render json: @act.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @act = Act.find(params[:id])
    @act.destroy
    head :no_content
  end

  private

  def act_params
    params.require(:act).permit(:title, :points)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login, :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def not_authenticated
    flash[:warning] = 'You have to authenticate to access this page.'
    redirect_to sign_in_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: [:welcome]

  def welcome
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = current_user.results.for(Date.today)
    @acts = current_user.acts
  end

  def data
    date = params[:date] || Date.today
    render json: current_user.results.for(date)
  end

  def create
    @result = Result.new(result_params)

    if @result.save
      render json: @result
    else
      render json: @result.errors, status: :unprocessable_entity
    end
  end

  def update
    @result = Result.find(params[:id])
    if @result.update(result_params)
      render json: @result
    else
      render json: @result.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy
    head :no_content
  end

  private

  def result_params
    params.require(:result).permit(:date, :act_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  end

  def create
    if login(params[:email], params[:password], params[:remember_me])
      flash[:success] = t('sessions.create.success')
      redirect_back_or_to authenticated_root_path
    else
      flash[:warning] = t('sessions.create.warning')
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = t('sessions.destroy.success')
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_and_redirect
    else
      flash[:danger] = t('users.create.danger')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  def login_and_redirect
    login(params[:user][:email], params[:user][:password])
    flash[:success] = t('users.create.success', name: @user.name)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', danger: 'alert-danger', warning: 'alert-warning', info: 'alert-info' }[flash_type]
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(
        content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} alert-dismissible") do
          concat content_tag(:button, '&times;'.html_safe, class: 'close', data: { dismiss: 'alert' })
          concat content_tag(:strong, message)
        end
      )
    end
    nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/acts/index.html.slim
= react_component 'Acts', { data: @acts, pageSize: 10 }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('head.title')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    javascript:
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          = link_to t('navigation.root'), nonauthenticated_root_path, class: 'navbar-brand'
        #navbar
          ul.nav.navbar-nav
            li = link_to t('navigation.acts'), acts_path if current_user
          ul.nav.navbar-nav.navbar-right
            - if current_user
              li
                span = current_user.name
              li = link_to t('navigation.sign_out'), sign_out_path, method: :delete
            - else
              li = link_to t('navigation.sign_up'), sign_up_path
              li = link_to t('navigation.sign_in'), sign_in_path
    .container.main
      = flash_messages
      = yield

app/views/pages/welcome.html.slim
h2 = 'Welcome, %username%'

app/views/results/index.html.slim
= react_component 'Results', { data: @results, pageSize: 10, acts: @acts, currentDate: Date.today.strftime('%Y-%m-%d') }

app/views/users/new.html.slim
.row
  .col-md-4.col-md-offset-4
    h1 = t('users.new.title')
    = form_for @user do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', required: true
      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control', required: true
      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control', required: true
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control', required: true
      = f.submit t('users.new.submit'), class: 'btn btn-primary btn'